using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.IO;
using System.Diagnostics;

namespace AnimeDL_GUI
{
    public partial class Form1 : Form
    {
        const string animeListFile = "animeList.txt";
        public Form1()
        {
            InitializeComponent();
            try
            {
                // Create an instance of StreamReader to read from a file.
                // The using statement also closes the StreamReader.
                using (StreamReader sr = new StreamReader(animeListFile))
                {
                    string line;

                    // Read and display lines from the file until 
                    // the end of the file is reached. 
                    while ((line = sr.ReadLine()) != null)
                    {
                        animeList.Items.Add(line);
                    }
                }

            }
            catch
            {

            }
        }

        private void button1_Click(object sender, EventArgs e)
        {
            animeList.Items.Add(animeInput.Text.ToString());
            animeInput.Text = "";
        }

        private void animeInput_TextChanged(object sender, EventArgs e)
        {

        }

        private void animeList_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void removeButton_Click(object sender, EventArgs e)
        {
            animeList.Items.RemoveAt(animeList.SelectedIndex);
        }

        bool SaveToFile(ListBox list)
        {
            using (StreamWriter sw = new StreamWriter(animeListFile))
            {
                foreach(string s in list.Items)
                    sw.WriteLine(s);
            }
            return true;
        }

        private void SaveList_Click(object sender, EventArgs e)
        {
            SaveToFile(animeList);
        }

        private void radioButton1_CheckedChanged(object sender, EventArgs e)
        {

        }

        private void radioButton2_CheckedChanged(object sender, EventArgs e)
        {

        }


        public string run_cmd(string cmd, string args)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = "PATH_TO_PYTHON_EXE";
            start.Arguments = string.Format("\"{0}\" \"{1}\"", cmd, args);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    return result;
                }
            }
        }

        private void download_Click(object sender, EventArgs e)
        {
            //run_cmd();
        }
    }
}
